name: Log Branch Merge

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  log_merge:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Verificar o histórico de commits para depuração
    - name: Debug Git log
      run: |
        echo "Checking commit history..."
        git log --oneline --graph --all

    # Obter o último commit de merge
    - name: Get the last merge commit
      run: |
        # Obter o hash do commit do merge ou indicar se não houver merge
        MERGE_COMMIT=$(git log -n 1 --merges --pretty=format:"%H" || echo "no merge found")
        if [ "$MERGE_COMMIT" = "no merge found" ]; then
          echo "No merge commit found, exiting..."
          exit 1
        fi
        echo "Merge Commit: $MERGE_COMMIT"

        # Obter a branch que foi mesclada
        MERGED_BRANCH=$(git log -n 1 --merges --pretty=format:"%P" | awk '{print $2}')
        echo "Merged Branch: $MERGED_BRANCH"
        echo "MERGED_BRANCH=$MERGED_BRANCH" >> $GITHUB_ENV

    # Obter a lista de arquivos alterados
    - name: Get the list of changed files
      run: |
        # Obter a lista de arquivos alterados no commit de merge
        FILES=$(git diff-tree --no-commit-id --name-only -r $MERGE_COMMIT)
        echo "Files changed: $FILES"
        echo "CHANGED_FILES=$FILES" >> $GITHUB_ENV

    # Verificar a criação do arquivo e atualizar o log
    - name: Update log file
      run: |
        echo "Verifying file creation..."
        touch merged_log.txt
        ls -l merged_log.txt

        # Formatar a entrada para o log
        echo "Branch merged: $MERGED_BRANCH" >> merged_log.txt
        echo "Files changed:" >> merged_log.txt
        echo "$CHANGED_FILES" >> merged_log.txt
        echo "---" >> merged_log.txt

        # Adicionar, commitar e enviar o arquivo atualizado ao repositório
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add merged_log.txt
        git commit -m "Update merged log with branch $MERGED_BRANCH"
        git push

    # Verificar as credenciais para push
    - name: Verify GitHub credentials
      run: |
        git remote -v
